// LoopStore - Loop 관리 상태
import { create } from 'zustand';
import { immer } from 'zustand/middleware/immer';
import { Category } from '../types.ts';

const useLoopStore = create(
  immer((set, get) => ({
    // State
    loops: [],
    
    // Computed values (getters)
    get loopsByPage() {
      const loops = get().loops;
      const byPage = {};
      loops.forEach(loop => {
        // Note: We'll need tags to determine which pages loops are on
        // This will be computed based on tag pages when needed
        if (!byPage['all']) byPage['all'] = [];
        byPage['all'].push(loop);
      });
      return byPage;
    },
    
    get autoGeneratedLoops() {
      return get().loops.filter(loop => loop.isAutoGenerated);
    },
    
    get manualLoops() {
      return get().loops.filter(loop => !loop.isAutoGenerated);
    },
    
    // Utility functions for instrument tag parsing
    parseInstrumentTag: (text) => {
      const cleanText = text.trim();
      
      // Match patterns: "PT-7083 C", "PZV-7012 A", "PIC-101", etc.
      const match = cleanText.match(/^([A-Z]{1,4})-?(\d+)[\s]*([A-Z]*)$/);
      if (match) {
        return {
          function: match[1].trim(),
          number: parseInt(match[2]),
          suffix: match[3].trim()
        };
      }
      
      // Try alternative pattern without dash: "PT7083C"
      const altMatch = cleanText.match(/^([A-Z]{1,4})(\d+)([A-Z]*)$/);
      if (altMatch) {
        return {
          function: altMatch[1].trim(),
          number: parseInt(altMatch[2]),
          suffix: altMatch[3].trim()
        };
      }
      
      return null;
    },
    
    generateLoopId: (instrumentTags) => {
      if (instrumentTags.length === 0) return null;
      
      const firstTag = instrumentTags[0];
      const parsed = get().parseInstrumentTag(firstTag.text);
      if (!parsed) return firstTag.text.charAt(0) + '-' + '000';
      
      // Find common function prefix among all tags
      let commonPrefix = parsed.function;
      for (const tag of instrumentTags.slice(1)) {
        const tagParsed = get().parseInstrumentTag(tag.text);
        if (tagParsed && tagParsed.number === parsed.number) {
          // Find common prefix between functions
          let i = 0;
          while (i < commonPrefix.length && i < tagParsed.function.length && 
                 commonPrefix[i] === tagParsed.function[i]) {
            i++;
          }
          commonPrefix = commonPrefix.substring(0, i);
        }
      }
      
      // Fallback to first letter if no common prefix
      if (commonPrefix.length === 0) {
        commonPrefix = parsed.function.charAt(0);
      }
      
      return `${commonPrefix}-${parsed.number}`;
    },
    
    // Actions
    setLoops: (loops) => set((state) => {
      state.loops = loops;
    }),
    
    addLoop: (loop) => set((state) => {
      state.loops.push(loop);
    }),
    
    addLoops: (newLoops) => set((state) => {
      state.loops.push(...newLoops);
    }),
    
    updateLoop: (loopId, updates) => set((state) => {
      const updatedLoops = state.loops.map(loop => 
        loop.id === loopId 
          ? { ...loop, ...updates }
          : loop
      );
      
      // Remove loops with no tags
      state.loops = updatedLoops.filter(loop => loop.tagIds && loop.tagIds.length > 0);
    }),
    
    deleteLoops: (loopIds) => set((state) => {
      const idsToDelete = new Set(loopIds);
      state.loops = state.loops.filter(loop => !idsToDelete.has(loop.id));
    }),
    
    deleteLoop: (loopId) => set((state) => {
      state.loops = state.loops.filter(loop => loop.id !== loopId);
    }),
    
    // 🟢 Complex auto generation functionality
    autoGenerateLoops: (allTags, uuidv4) => set((state) => {
      const instrumentTags = allTags.filter(t => t.category === Category.Instrument);
      
      if (instrumentTags.length === 0) {
        return;
      }

      // Group by 1-letter prefix and number
      const oneLetterGroups = new Map();
      
      for (const tag of instrumentTags) {
        const parsed = get().parseInstrumentTag(tag.text);
        if (!parsed) continue;
        
        const oneLetterKey = `${parsed.function.charAt(0)}-${parsed.number}`;
        if (!oneLetterGroups.has(oneLetterKey)) {
          oneLetterGroups.set(oneLetterKey, []);
        }
        oneLetterGroups.get(oneLetterKey).push(tag);
      }
      
      // Create loops from groups with multiple tags
      const newLoops = [];
      oneLetterGroups.forEach((groupTags) => {
        if (groupTags.length > 1) {
          const loopId = get().generateLoopId(groupTags);
          if (loopId) {
            const newLoop = {
              id: loopId,
              tagIds: groupTags.map(t => t.id),
              createdAt: new Date().toISOString(),
              isAutoGenerated: true
            };
            newLoops.push(newLoop);
          }
        }
      });
      
      if (newLoops.length > 0) {
        state.loops.push(...newLoops);
      }
    }),
    
    // 🟢 Complex manual generation with confirmation
    autoGenerateLoopsWithConfirmation: (tags, pageFilter, showConfirmation, alert, uuidv4) => {
      const instrumentTags = tags.filter(t => 
        t.category === Category.Instrument && 
        (pageFilter ? t.page === pageFilter : true)
      );
      
      if (instrumentTags.length === 0) {
        alert('No instrument tags found to create loops.');
        return;
      }

      showConfirmation(
        `This will automatically create loops from ${instrumentTags.length} instrument tags based on function prefix and number matching. Continue?`,
        () => {
          set((state) => {
            // First, group by 1-letter prefix and number
            const oneLetterGroups = new Map();
            
            for (const tag of instrumentTags) {
              const parsed = get().parseInstrumentTag(tag.text);
              if (!parsed) continue;
              
              const oneLetterKey = `${parsed.function.charAt(0)}-${parsed.number}`;
              if (!oneLetterGroups.has(oneLetterKey)) {
                oneLetterGroups.set(oneLetterKey, []);
              }
              oneLetterGroups.get(oneLetterKey).push(tag);
            }
            
            // Use 1-letter groups as the primary grouping method
            const loopGroups = oneLetterGroups;
            
            // Create loops from groups with multiple tags
            const newLoops = [];
            const existingLoopIds = new Set(state.loops.map(l => l.id));
            
            for (const [groupKey, groupTags] of loopGroups.entries()) {
              if (groupTags.length > 1) {
                const loopId = get().generateLoopId(groupTags) || groupKey;
                
                // Skip if loop already exists
                if (existingLoopIds.has(loopId)) continue;
                
                newLoops.push({
                  id: loopId,
                  tagIds: groupTags.map(t => t.id),
                  createdAt: new Date().toISOString(),
                  isAutoGenerated: true
                });
              }
            }
            
            if (newLoops.length > 0) {
              state.loops.push(...newLoops);
              alert(`Created ${newLoops.length} new loops from ${newLoops.reduce((sum, loop) => sum + loop.tagIds.length, 0)} instrument tags.`);
            } else {
              alert('No new loops could be created. They may already exist or no matching groups were found.');
            }
          });
        }
      );
    },
    
    // 🟢 Manual loop creation
    manualCreateLoop: (selectedTagIds, tags, alert) => {
      const selectedInstrumentTags = tags.filter(t => 
        selectedTagIds.includes(t.id) && t.category === Category.Instrument
      );
      
      if (selectedInstrumentTags.length < 2) {
        alert('Please select at least 2 instrument tags to create a loop.');
        return;
      }
      
      const loopId = get().generateLoopId(selectedInstrumentTags);
      if (!loopId) {
        alert('Could not generate loop ID from selected tags.');
        return;
      }
      
      // Check if loop already exists
      const existingLoop = get().loops.find(l => l.id === loopId);
      if (existingLoop) {
        alert(`Loop "${loopId}" already exists.`);
        return;
      }
      
      const newLoop = {
        id: loopId,
        tagIds: selectedInstrumentTags.map(t => t.id),
        createdAt: new Date().toISOString(),
        isAutoGenerated: false
      };
      
      set((state) => {
        state.loops.push(newLoop);
      });
      
      alert(`Created loop "${loopId}" with ${selectedInstrumentTags.length} instrument tags.`);
    },
    
    // Query helpers
    getLoopById: (id) => {
      return get().loops.find(loop => loop.id === id);
    },
    
    getLoopsContainingTag: (tagId) => {
      return get().loops.filter(loop => loop.tagIds.includes(tagId));
    },
    
    // Statistics
    get stats() {
      const loops = get().loops;
      const totalLoops = loops.length;
      const autoGenerated = loops.filter(loop => loop.isAutoGenerated).length;
      const manual = totalLoops - autoGenerated;
      
      return {
        total: totalLoops,
        autoGenerated,
        manual,
        totalTags: loops.reduce((sum, loop) => sum + loop.tagIds.length, 0)
      };
    }
  }))
);

export default useLoopStore;