export const Category = {
  Equipment: 'Equipment',
  Line: 'Line',
  Instrument: 'Instrument',
  DrawingNumber: 'DrawingNumber',
  NotesAndHolds: 'NotesAndHolds',
  SpecialItem: 'SpecialItem',
  OffPageConnector: 'OffPageConnector',
  Uncategorized: 'Uncategorized',
} as const;

export type CategoryType = typeof Category[keyof typeof Category];

export const RelationshipType = {
  Connection: 'Connection', // A -> B
  Installation: 'Installation', // A is on B
  Annotation: 'Annotation', // Tag -> Raw Text Item
  Note: 'Note', // Equipment/Line/Instrument -> NotesAndHolds Tag
  Description: 'Description', // NotesAndHolds Tag -> Description
  EquipmentShortSpec: 'EquipmentShortSpec', // Equipment Tag -> Equipment Short Spec
  OffPageConnection: 'OffPageConnection', // OPC Tag <-> OPC Tag (bidirectional)
} as const;

export type RelationshipTypeValue = typeof RelationshipType[keyof typeof RelationshipType];

// Comment system types
export interface Comment {
  id: string;
  targetId: string;        // 대상 엔티티 ID
  targetType: 'tag' | 'description' | 'equipmentSpec' | 'relationship' | 'loop';
  content: string;         // 댓글 내용
  author: string;          // 작성자 (기본값: "User")
  timestamp: number;       // 작성 시간
  isResolved: boolean;     // 해결됨 여부
  priority: 'low' | 'medium' | 'high'; // 우선순위
}

export type CommentTargetType = Comment['targetType'];
export type CommentPriority = Comment['priority'];

// Visibility settings interface
export interface VisibilitySettings {
  tags: {
    equipment: boolean;
    line: boolean;
    instrument: boolean;
    drawingNumber: boolean;
    notesAndHolds: boolean;
    specialItem: boolean;
    offPageConnector: boolean;
  };
  descriptions: boolean;
  equipmentShortSpecs: boolean;
  relationships: {
    connection: boolean;
    installation: boolean;
    annotation: boolean;
    note: boolean;
    offPageConnection: boolean;
  };
}

// Color settings interface
export interface ColorSettings {
  entities: {
    equipment: string;
    line: string;
    instrument: string;
    drawingNumber: string;
    notesAndHolds: string;
    specialItem: string;
    offPageConnector: string;
    uncategorized: string;
    description: string;        // Description entity color
    equipmentShortSpec: string;  // Equipment Short Spec entity color
  };
  relationships: {
    connection: string;         // Connection arrow line
    installation: string;       // Installation arrow line
    annotation: string;         // Annotation line & linked raw text
    note: string;              // Note relationship line
    offPageConnection: string; // OPC relationship line
  };
  highlights: {
    primary: string;        // Red-500 (primary selection/ping)
    note: string;          // Violet-500 (note-related items)
    equipment: string;     // Orange-500 (equipment-related items)
    description: string;   // Purple-500 (description items)
    related: string;       // Indigo-500 (related tags)
    // Legacy support
    noteRelated: string;   // Keep for backward compatibility
    selected: string;      // Keep for backward compatibility
  };
}

// Core data structure interfaces
export interface BoundingBox {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export interface RawTextItem {
  id: string;
  text: string;
  page: number;
  bbox: BoundingBox;
}

export interface Tag {
  id: string;
  text: string;
  page: number;
  bbox: BoundingBox;
  category: CategoryType;
  sourceItems: RawTextItem[];
  isReviewed?: boolean;
}

export interface Description {
  id: string;
  text: string;
  page: number;
  bbox: BoundingBox;
  sourceItems: (Tag | RawTextItem)[];
  metadata: {
    type: 'Note' | 'Hold';
    scope: 'General' | 'Specific';
    number: number;
  };
}

export interface EquipmentShortSpec {
  id: string;
  text: string;
  page: number;
  bbox: BoundingBox;
  sourceItems: (Tag | RawTextItem)[];
  metadata: {
    originalEquipmentTag: Tag;
    service: string;
  };
}

export interface Loop {
  id: string; // e.g., "PI-101", "FT-201"
  name?: string; // Optional custom name
  tagIds: string[]; // Array of instrument tag IDs in this loop
  createdAt: string; // ISO timestamp
  isAutoGenerated: boolean; // true for auto-generated, false for manual
}

export interface Relationship {
  id: string;
  from: string;
  to: string;
  type: RelationshipTypeValue;
}

// Component prop interfaces
export interface ConfirmModalProps {
  isOpen: boolean;
  message: string;
  onConfirm: () => void;
  onCancel: () => void;
}

export interface HeaderProps {
  onReset: () => void;
  hasData: boolean;
  onOpenSettings: () => void;
  onImportProject: (file: File) => void;
  onExportProject: () => void;
  pdfDoc: any; // TODO: Add proper PDF.js types
  currentPage: number;
  setCurrentPage: (page: number) => void;
  scale: number;
  setScale: (scale: number) => void;
  mode: ViewMode;
  onToggleSidePanel: () => void;
  onToggleOPCPanel: () => void;
  onAutoLinkDescriptions: () => void;
  onAutoLinkNotesAndHolds: () => void;
  onAutoLinkEquipmentShortSpecs: () => void;
  onAutoLinkAll: () => void;
  onRemoveWhitespace: () => void;
  showAllRelationships: boolean;
  setShowAllRelationships: (show: boolean) => void;
  showOnlySelectedRelationships: boolean;
  setShowOnlySelectedRelationships: (show: boolean) => void;
}

export type ViewMode = 'select' | 'connect' | 'manualCreate';

export interface PdfUploadProps {
  onFileSelect: (file: File) => void;
}

export interface WorkspaceProps {
  pdfDoc: any; // TODO: Add proper PDF.js types
  tags: Tag[];
  setTags: React.Dispatch<React.SetStateAction<Tag[]>>;
  relationships: Relationship[];
  setRelationships: React.Dispatch<React.SetStateAction<Relationship[]>>;
  rawTextItems: RawTextItem[];
  descriptions: Description[];
  setDescriptions: React.Dispatch<React.SetStateAction<Description[]>>;
  equipmentShortSpecs: EquipmentShortSpec[];
  setEquipmentShortSpecs: React.Dispatch<React.SetStateAction<EquipmentShortSpec[]>>;
  onCreateTag: (itemsToConvert: RawTextItem[], category: CategoryType) => void;
  onCreateManualTag: (tagData: ManualTagData) => void;
  onCreateDescription: (selectedItems: (Tag | RawTextItem)[]) => void;
  onCreateEquipmentShortSpec: (selectedItems: (Tag | RawTextItem)[]) => void;
  onDeleteTags: (tagIds: string[]) => void;
  onUpdateTagText: (tagId: string, newText: string) => void;
  onDeleteDescriptions: (descriptionIds: string[]) => void;
  onUpdateDescription: (id: string, text: string, metadata: Description['metadata']) => void;
  onDeleteEquipmentShortSpecs: (equipmentShortSpecIds: string[]) => void;
  onUpdateEquipmentShortSpec: (id: string, text: string, metadata?: EquipmentShortSpec['metadata']) => void;
  onMergeRawTextItems: (itemIds: string[]) => void;
  onDeleteRawTextItems: (itemIds: string[]) => void;
  onUpdateRawTextItemText: (itemId: string, newText: string) => void;
  onAutoLinkDescriptions: () => void;
  onAutoLinkNotesAndHolds: () => void;
  onAutoLinkEquipmentShortSpecs: () => void;
  showConfirmation: (message: string, onConfirm: () => void) => void;
  currentPage: number;
  setCurrentPage: (page: number) => void;
  scale: number;
  setScale: (scale: number) => void;
  mode: ViewMode;
  setMode: (mode: ViewMode) => void;
  relationshipStartTag: Tag | null;
  setRelationshipStartTag: (tag: Tag | null) => void;
  showRelationships: boolean;
  setShowRelationships: (show: boolean) => void;
  isSidePanelVisible: boolean;
  isOPCPanelVisible: boolean;
  visibilitySettings: VisibilitySettings;
  updateVisibilitySettings: (settings: VisibilitySettings) => void;
  showAutoLinkRanges: boolean;
  tolerances: ToleranceConfig;
  loops: Loop[];
  setLoops: React.Dispatch<React.SetStateAction<Loop[]>>;
  onCreateHoldDescription: (selectedItems: (Tag | RawTextItem)[]) => void;
  onDeleteLoops: (loopIds: string[]) => void;
  onUpdateLoop: (id: string, name: string, tags: string[], notes?: string) => void;
  onAutoGenerateLoops: () => void;
  onManualCreateLoop: () => void;
  toggleTagVisibility: (category: keyof VisibilitySettings['tags']) => void;
  toggleRelationshipVisibility: (type: keyof VisibilitySettings['relationships']) => void;
  toggleAllTags: (show: boolean) => void;
  toggleAllRelationships: (show: boolean) => void;
  showAllRelationships: boolean;
  setShowAllRelationships: (show: boolean) => void;
  showOnlySelectedRelationships: boolean;
  setShowOnlySelectedRelationships: (show: boolean) => void;
}

export interface ManualTagData {
  text: string;
  bbox: BoundingBox;
  page: number;
  category: CategoryType;
}

// Settings and configuration interfaces
export interface InstrumentPattern {
  func: string;
  num: string;
}

export interface PatternConfig {
  [Category.Equipment]: string;
  [Category.Line]: string;
  [Category.Instrument]: InstrumentPattern;
  [Category.DrawingNumber]: string;
  [Category.NotesAndHolds]: string;
  [Category.SpecialItem]: string;
  [Category.OffPageConnector]: string;
}

export interface ToleranceConfig {
  [Category.Instrument]: {
    vertical: number;
    horizontal: number;
    autoLinkDistance: number;
  };
}

export interface HyphenSettings {
  equipment: boolean;
  line: boolean;
  instrument: boolean;
  drawingNumber: boolean;
  notesAndHolds: boolean;
  specialItem: boolean;
  offPageConnector: boolean;
}

export interface AppSettings {
  autoGenerateLoops: boolean;
  autoRemoveWhitespace: boolean;
  hyphenSettings: HyphenSettings;
}

export interface SettingsModalProps {
  patterns: PatternConfig;
  tolerances: ToleranceConfig;
  appSettings: AppSettings;
  colorSettings: ColorSettings;
  onSaveOnly: (patterns: PatternConfig, tolerances: ToleranceConfig, appSettings: AppSettings, colorSettings: ColorSettings) => void;
  onSaveAndRescan: (patterns: PatternConfig, tolerances: ToleranceConfig, appSettings: AppSettings, colorSettings: ColorSettings, activeTab: string) => void;
  onClose: () => void;
}

// Project data interfaces
export interface ProjectData {
  pdfFileName: string;
  exportDate: string;
  tags: Tag[];
  relationships: Relationship[];
  rawTextItems: RawTextItem[];
  descriptions: Description[];
  equipmentShortSpecs: EquipmentShortSpec[];
  comments: Comment[];
  settings: {
    patterns: PatternConfig;
    tolerances: ToleranceConfig;
    appSettings: AppSettings;
  };
}

// Progress tracking interface
export interface ProcessingProgress {
  current: number;
  total: number;
}
